version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: doctor-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8083:8083"
    networks:
      - app-network


volumes:
  db_data:

networks:
  app-network:
    external: true