import type { Metadata } from "next";
import "./globals.css";
import { ContextProvider } from "@/_context/Providers";



export const metadata: Metadata = {
  title: "Medihub",
  description: "Generated by create next app",
  icons: {
    icon: "logo-svg-app.svg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (

    <html lang="en">
      <body className={`antialiased`}>
        <ContextProvider>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}