services:
  db_patient:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB_PATIENT}
    ports:
      - "5438:5432"
    volumes:
      - patient_data:/var/lib/postgresql/data

  patient-app:
    build: .
    depends_on:
      - db_patient
    env_file:
      - .env
    ports:
      - "8085:8085"

volumes:
  patient_data: