version: "3.8"

services:
  db:
    image: postgres:16
    container_name: fhir-db
    environment:
      - POSTGRES_DB=hapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  ehr-server:
    build: ./ehr-server
    container_name: ehr-server
    ports:
      - "8085:8080"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - JAVA_TOOL_OPTIONS=-Xms128m -Xmx512m
      - spring.datasource.hikari.maximum-pool-size=3
      - hapi.fhir.validation.enabled=false
      - hapi.fhir.indexing.enabled=false
    networks:
      - app-network

  api:
    build: .
    container_name: ehr-app
    depends_on:
      - ehr-server
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - FHIR_SERVER_URL=http://ehr-server:8080/fhir
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  postgres_data:

